from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.colors import navy
from reportlab.lib.units import inch
from reportlab.lib.styles import ParagraphStyle
from datetime import datetime


def generate_student_report(user_name):

    filename = f"{user_name}_Student_Report.pdf"

    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    title = ParagraphStyle(
        "Title",
        parent=styles["Heading1"],
        alignment=TA_CENTER,
        textColor=navy,
        spaceAfter=20
    )

    story = []

    story.append(Paragraph("TalentSphere Elevate", title))
    story.append(Paragraph("Student Progress Report", styles["Heading2"]))
    story.append(Spacer(1, 0.2 * inch))

    story.append(Paragraph(f"<b>Name:</b> {user_name}", styles["BodyText"]))
    story.append(Paragraph("<b>Category:</b> High School Student", styles["BodyText"]))
    story.append(
        Paragraph(
            f"<b>Date:</b> {datetime.now().strftime('%d-%m-%Y')}",
            styles["BodyText"]
        )
    )

    story.append(Spacer(1, 0.2 * inch))

    story.append(Paragraph("<b>Overall Progress</b>", styles["Heading2"]))

    story.append(Paragraph("Learning Progress : 75%", styles["BodyText"]))
    story.append(Paragraph("Career Readiness : Beginner", styles["BodyText"]))
    story.append(Paragraph("Tasks Completed : 12", styles["BodyText"]))
    story.append(Paragraph("Coding Progress : 60%", styles["BodyText"]))
    story.append(Paragraph("Aptitude Score : 80%", styles["BodyText"]))

    story.append(Spacer(1, 0.2 * inch))

    story.append(Paragraph("<b>Career Recommendation</b>", styles["Heading2"]))
    story.append(
        Paragraph(
            "Artificial Intelligence Engineer",
            styles["BodyText"]
        )
    )

    story.append(Spacer(1, 0.2 * inch))

    story.append(Paragraph("<b>Module Summary</b>", styles["Heading2"]))

    modules = [
        "Career Explorer",
        "Career Quiz",
        "Interest Assessment",
        "Future Skills Roadmap",
        "Daily Learning",
        "Coding Basics",
        "Aptitude Practice",
        "Communication Skills",
        "Goal Tracker",
        "Mentor"
    ]

    for module in modules:
        story.append(
            Paragraph(f"• {module}", styles["BodyText"])
        )

    story.append(Spacer(1, 0.2 * inch))

    story.append(Paragraph("<b>Mentor Recommendation</b>", styles["Heading2"]))

    story.append(
        Paragraph(
            "Continue learning Python, improve communication skills, practice aptitude daily, and complete your learning roadmap.",
            styles["BodyText"]
        )
    )

    story.append(Spacer(1, 0.3 * inch))

    story.append(
        Paragraph(
            "<b>Generated by TalentSphere Elevate</b>",
            styles["BodyText"]
        )
    )

    doc.build(story)

    return filename


def generate_college_report(user_name, career_readiness, coding_progress, resume_score, project_count, missing_skills, completed_tasks_count, cert_count):
    filename = f"{user_name}_College_Performance_Report.pdf"
    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    title = ParagraphStyle(
        "Title",
        parent=styles["Heading1"],
        alignment=TA_CENTER,
        textColor=navy,
        spaceAfter=20
    )

    story = []

    story.append(Paragraph("TalentSphere Elevate", title))
    story.append(Paragraph("College Performance Report Card", styles["Heading2"]))
    story.append(Spacer(1, 0.2 * inch))

    story.append(Paragraph(f"<b>Name:</b> {user_name}", styles["BodyText"]))
    story.append(Paragraph("<b>Category:</b> College Student", styles["BodyText"]))
    story.append(
        Paragraph(
            f"<b>Date:</b> {datetime.now().strftime('%d-%m-%Y')}",
            styles["BodyText"]
        )
    )

    story.append(Spacer(1, 0.2 * inch))
    story.append(Paragraph("<b>Overall Performance Metrics</b>", styles["Heading2"]))

    story.append(Paragraph(f"Career Readiness: {career_readiness}%", styles["BodyText"]))
    story.append(Paragraph(f"Coding Progress: {coding_progress}%", styles["BodyText"]))
    story.append(Paragraph(f"Resume Completeness Score: {resume_score}/100", styles["BodyText"]))
    story.append(Paragraph(f"Logged Projects: {project_count}", styles["BodyText"]))
    story.append(Paragraph(f"Completed Planner Tasks: {completed_tasks_count}", styles["BodyText"]))
    story.append(Paragraph(f"Earned Certifications: {cert_count}", styles["BodyText"]))

    story.append(Spacer(1, 0.2 * inch))
    story.append(Paragraph("<b>Skills Analysis</b>", styles["Heading2"]))
    if missing_skills:
        story.append(Paragraph(f"<b>Identified Skill Gaps:</b> {', '.join(missing_skills)}", styles["BodyText"]))
    else:
        story.append(Paragraph("<b>Identified Skill Gaps:</b> None. Core skills profile complete.", styles["BodyText"]))

    story.append(Spacer(1, 0.2 * inch))
    story.append(Paragraph("<b>Career Recommendation</b>", styles["Heading2"]))
    if missing_skills:
        story.append(Paragraph(f"Focus on resolving the skill gaps in {missing_skills[0]} to align with Full-Stack developer matching metrics.", styles["BodyText"]))
    else:
        story.append(Paragraph("Fully ready for software engineering interviews. Practice system design and algorithmic challenges.", styles["BodyText"]))

    story.append(Spacer(1, 0.3 * inch))

    story.append(
        Paragraph(
            "<b>Generated by TalentSphere Elevate</b>",
            styles["BodyText"]
        )
    )

    doc.build(story)

    return filename


def generate_professional_report(user_name, company, role, exp, promotion_readiness, salary_growth, top_match, skills_dict, cert_list):
    filename = f"{user_name}_Professional_Growth_Report.pdf"
    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    title = ParagraphStyle(
        "Title",
        parent=styles["Heading1"],
        alignment=TA_CENTER,
        textColor=navy,
        spaceAfter=20
    )

    story = []

    story.append(Paragraph("TalentSphere Elevate", title))
    story.append(Paragraph("Working Professional Growth & Career Analysis Report", styles["Heading2"]))
    story.append(Spacer(1, 0.2 * inch))

    story.append(Paragraph(f"<b>Name:</b> {user_name}", styles["BodyText"]))
    story.append(Paragraph(f"<b>Current Role:</b> {role} @ {company}", styles["BodyText"]))
    story.append(Paragraph(f"<b>Total Experience:</b> {exp} Years", styles["BodyText"]))
    story.append(Paragraph(f"<b>Date:</b> {datetime.now().strftime('%d-%m-%Y')}", styles["BodyText"]))

    story.append(Spacer(1, 0.2 * inch))
    story.append(Paragraph("<b>Executive Summary & AI Key Metrics</b>", styles["Heading2"]))

    story.append(Paragraph(f"• <b>Promotion Readiness:</b> {promotion_readiness}%", styles["BodyText"]))
    story.append(Paragraph(f"• <b>Salary Growth Potential:</b> {salary_growth}", styles["BodyText"]))
    story.append(Paragraph(f"• <b>Top Target Role Match:</b> {top_match}", styles["BodyText"]))

    story.append(Spacer(1, 0.2 * inch))
    story.append(Paragraph("<b>Professional Skill Assessment</b>", styles["Heading2"]))
    for skill_name, score in skills_dict.items():
        story.append(Paragraph(f"• <b>{skill_name}:</b> {score}%", styles["BodyText"]))

    story.append(Spacer(1, 0.2 * inch))
    story.append(Paragraph("<b>Recommended Certifications & Action Plan</b>", styles["Heading2"]))
    for cert in cert_list:
        cname = cert if isinstance(cert, str) else cert.get("cert_name", "")
        cstat = cert.get("status", "Recommended") if isinstance(cert, dict) else "Recommended"
        story.append(Paragraph(f"• {cname} (Status: {cstat})", styles["BodyText"]))

    story.append(Spacer(1, 0.2 * inch))
    story.append(Paragraph("<b>AI Career Transition Advice</b>", styles["Heading2"]))
    story.append(
        Paragraph(
            f"Based on your {exp} years of backend experience, focus on Cloud Computing (AWS/Kubernetes) and System Design architecture to prepare for the {top_match} transition within 90 days.",
            styles["BodyText"]
        )
    )

    story.append(Spacer(1, 0.3 * inch))
    story.append(
        Paragraph(
            "<b>Generated by TalentSphere Elevate - Working Professional Module</b>",
            styles["BodyText"]
        )
    )

    doc.build(story)

    return filename